server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #当前数据源操作类型
    driverClassName: com.mysql.jdbc.Driver          #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?userUnicode=true&charcterEncoding=utf-8&useSSL=false
    username: root
    password: coadceth@Data@contre5


eureka:
  client:
    #表示是否将自己注册进eurekaserver默认true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    #集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true       #访问路径可以显示IP地址

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yjp.springcloud.entities    #所有entity别名类所在包